### ISSUE TITLE
Request URL: http://ip:35729/livereload.js 404

### ISSUE THREAD

**Issue by xuthus5** [IanSmith123/gitbook-docker#1]
提示找不到livereload.js插件，该如何处理

**Comment by IanSmith123** [comment]
![](http://oqyjccf1n.bkt.clouddn.com/20180623-145835.png)
刚刚完整测试了一遍，未遇到问题。

请详细描述如何复现所遇到的问题，谢谢。 🤷‍♂️

**Comment by xuthus5** [comment]
当我构建完后，访问服务，会出现加载缓慢的现象，通过开发者工具，很容易发现一个资源无法访问到。但是我无法保证自己可以解决这个问题。当我手动修改加载这个文件的插件位置时，在下一次的运行中会删除这个修改。 
![screenshot_20180623_232522](https://user-images.githubusercontent.com/22839236/41811202-e110ef84-773d-11e8-9f48-97fc8efa1b93.png)

**Comment by IanSmith123** [comment]
livereload.js会请求主机的`35729`端口，docker中未增加映射，问题已修复
感谢你提交的的issue
 👍
