### ISSUE TITLE
怎么进入容器

### ISSUE THREAD

**Issue by nilsir** [IanSmith123/gitbook-docker#2]
我要搭建一套内网访问的, 需要使用docker里边的公钥, 怎么弄呢

**Comment by IanSmith123** [comment]
关于docker的使用，请查看docker的[文档](https://docs.docker.com/engine/reference/commandline/exec/)

**Comment by nilsir** [comment]
sudo docker exec -itd node_gitbook bash
我这样进不了容器, 怎么才能正常进入呢

**Comment by IanSmith123** [comment]
```
sudo docker exec -it node_gitbook bash
```
